CREATE TABLE IF NOT EXISTS health_records(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    record_date DATE NOT NULL,
    weight_kg DECIMAL(5,2) NULL,
    note VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_health_records_record_date UNIQUE (record_date)
);